export const userType = {
    SET_USER_DATA: 'SET_USER_DATA',
    FETCH_DATA_START: 'FETCH_DATA_START',
    FETCH_DATA_LOADING: 'FETCH_DATA_LOADING',
    FETCH_DATA_FAIL: 'FETCH_DATA_FAIL',
    SET_DATA_USER: 'SET_DATA_USER',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
}